language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install:
- phpenv rehash
- travis_retry composer self-update
- travis_retry composer require satooshi/php-coveralls "^1" --no-update --dev
- travis_retry composer install
script:
- phpunit
cache:
  apt: true
  directories:
  - vendor
